theme: jekyll-theme-minimal
title: "MS Annika Spectral Library exporter"
description: "The MS Annika Spectral Library exporter generates a spectral library for Spectronaut from MS Annika results."
logo: https://raw.githubusercontent.com/hgb-bin-proteomics/MSAnnika/master/logo/annika_logo.png
show_downloads: "true"
github:
  zip_url: https://github.com/hgb-bin-proteomics/MSAnnika_Spectral_Library_exporter/archive/master.zip
  tar_url: https://github.com/hgb-bin-proteomics/MSAnnika_Spectral_Library_exporter/archive/master.tar.gz
